action_id: trunk-whoami
date: 2025-02-24 05:31:44
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1740375104
full_timestamp:
  nanos: 209691000
  seconds: 1740375104
trunk_version: 1.22.10
